### PR TITLE
Fix problem with babel6 and react-transform-hmr for server.js script.

### PR DESCRIPTION
**Pull request by nodkz**
Problem: config.module.loaders pointed in same object in memory. So react-transform (in start.js) applies for server config too, in despite of x.target !== 'node'.

### CODE REVIEW

**Comment by nodkz** [comment]
This patch solve such error:

```
/Users/nod/www/rabota/node_modules/react-transform-hmr/lib/index.js:51
    throw new Error('locals[0] does not appear to be a `module` object with Hot Module ' + 'replacement API enabled. You should disable react-transform-hmr in ' + 'production by using `env` section in Babel configuration. See the ' + 'example in README: https://github.com/gaearon/react-transform-hmr');
          ^
Error: locals[0] does not appear to be a `module` object with Hot Module replacement API enabled. You should disable react-transform-hmr in production by using `env` section in Babel configuration. See the example in README: https://github.com/gaearon/react-transform-hmr
    at proxyReactComponents (/Users/nod/www/rabota/node_modules/react-transform-hmr/lib/index.js:51:11)
    at Object.<anonymous> (/Users/nod/www/rabota/build/server.js:397:61)
    at Object.module.exports.module.exports.module.deprecate (/Users/nod/www/rabota/build/server.js:489:32)
    at __webpack_require__ (/Users/nod/www/rabota/build/webpack:/webpack/bootstrap 248cbd7ff71325511587:19:1)
    at Object.<anonymous> (/Users/nod/www/rabota/build/server.js:221:15)
    at __webpack_require__ (/Users/nod/www/rabota/build/webpack:/webpack/bootstrap 248cbd7ff71325511587:19:1)
    at Object.<anonymous> (/Users/nod/www/rabota/build/webpack:/webpack/bootstrap 248cbd7ff71325511587:39:1)
    at __webpack_require__ (/Users/nod/www/rabota/build/webpack:/webpack/bootstrap 248cbd7ff71325511587:19:1)
    at /Users/nod/www/rabota/build/webpack:/webpack/bootstrap 248cbd7ff71325511587:39:1
    at Object.<anonymous> (/Users/nod/www/rabota/build/webpack:/webpack/bootstrap 248cbd7ff71325511587:39:1)
```

**Comment by koistya** [comment]
Nice catch, thanks!

**Comment by koistya** [comment]
I would just replace `lodash.merge` and `lodash.clonedeep` with `extend` module. @nodkz, what do you think?

**Comment by nodkz** [comment]
If same behavior and webpack config stay in one file, then your solution will be better. 
I honestly do not know how `extend` works. 
And less packages in package.json is good catch.

**Comment by nodkz** [comment]
If you say about this module https://github.com/dreamerslab/node.extend
Then I think it's not good, because `lodash` internally is using at least in `babel-core`.
So have one more module with same behavior in node_modules is not good solution.

**Comment by koistya** [comment]
This one: https://www.npmjs.com/package/extend

**Comment by nodkz** [comment]
Good lib. It already used in `request` module, which used in `browsync`, `babel-cli`, `babel-eslint`, `globals` and others.

That is why it is so popular. Must have!

**Comment by nodkz** [comment]
Tested, and it works as expected in my build.

**Comment by koistya** [comment]
@nodkz :+1:

**Pull request merged**
